# --- !Ups
CREATE TABLE User
(
    ID       INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(255),
    EMAIL    VARCHAR(255),
    PASSWORD VARCHAR(255)
);

CREATE TABLE Product
(
    ID          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME        VARCHAR(255),
    PRICE       DOUBLE,
    DESCRIPTION TEXT
);

CREATE TABLE CartElement
(
    ID         INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    CART_ID    INTEGER,
    PRODUCT_ID INTEGER,
    QUANTITY   INTEGER
);

CREATE TABLE Cart
(
    ID      INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER
);


CREATE TABLE Order
(
    ID      INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    CART_ID INTEGER
);

CREATE TABLE Payment
(
    ID       INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    ORDER_ID INTEGER,
    IS_PAYED BOOLEAN,
    AMOUNT   DOUBLE
);

CREATE TABLE ProductRating
(
    ID          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    PRODUCT_ID  INTEGER,
    ITEM_SCORE  DOUBLE
);

CREATE TABLE Discount
(
    ID          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    PRODUCT_ID  INTEGER,
    AMOUNT      DOUBLE
);

# --- !Downs
DROP TABLE User;
DROP TABLE Product;
DROP TABLE RecordInCart;
DROP TABLE Cart;
DROP TABLE Order;
DROP TABLE Payment;
DROP TABLE ProductRating;
DROP TABLE Discount;